"""author table

Revision ID: 3b0c62540d35
Revises: 7ace0aef0a89
Create Date: 2023-10-16 23:03:18.242981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0c62540d35'
down_revision = '7ace0aef0a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=64), nullable=True))
        batch_op.drop_index('ix_user_username')
        batch_op.create_index(batch_op.f('ix_user_author'), ['author'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_author'))
        batch_op.create_index('ix_user_username', ['username'], unique=False)
        batch_op.drop_column('author')

    # ### end Alembic commands ###
