"""author table

Revision ID: 3c0555f397c0
Revises: 3eae8e873169
Create Date: 2023-10-10 07:25:55.171349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0555f397c0'
down_revision = '3eae8e873169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookss', sa.String(length=140), nullable=True))
        batch_op.drop_column('books')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('bookss')

    # ### end Alembic commands ###
