"""author table

Revision ID: 3eae8e873169
Revises: 63bf40425f15
Create Date: 2023-10-10 07:21:01.238641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eae8e873169'
down_revision = '63bf40425f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_books')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_books', ['books'], unique=False)

    # ### end Alembic commands ###
