"""author table

Revision ID: 7ace0aef0a89
Revises: 3c0555f397c0
Create Date: 2023-10-10 07:26:21.434166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ace0aef0a89'
down_revision = '3c0555f397c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books', sa.String(length=140), nullable=True))
        batch_op.drop_column('bookss')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookss', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('books')

    # ### end Alembic commands ###
