"""new author

Revision ID: 857abc97f7ce
Revises: 4aac7b2aef25
Create Date: 2023-10-10 05:32:31.026689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '857abc97f7ce'
down_revision = '4aac7b2aef25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('books')

    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
